CREATE USER APP_NAME_UND_app WITH PASSWORD 'DB_PASSWORD';

ALTER ROLE APP_NAME_UND_app WITH CREATEDB;

CREATE DATABASE APP_NAME_UND_main;

GRANT ALL PRIVILEGES ON DATABASE APP_NAME_UND_main TO APP_NAME_UND_app;

-- must have this alter owner otherwise permission denied
ALTER DATABASE APP_NAME_UND_main OWNER TO APP_NAME_UND_app;
