# Server configurations
server:
  name: "jarvis"
  host: "0.0.0.0"
  port: 8080
  grpcPort: 8081

# Database credentials
database:
  host: "localhost"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  maxIdleConns: 20
  maxOpenConns: 200

replica:
  host: "localhost"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  maxIdleConns: 20
  maxOpenConns: 800

# Logging
log:
  level: "ERROR"

# WorkerPool
workerpool:
  maxPoolSize: 20
  maxQueueSize: 40
