# Server configurations
server:
  name: "jarvis"
  host: "localhost"
  port: 8000

# Database credentials
database:
  user: "admin"
  password: "iori2008"
  host: "tcp(jarvis-database-instance-1.cjemwmweprl0.ap-southeast-1.rds.amazonaws.com:3306)"
  database: "jarvis"
  maxLifetime:  10
  maxIdleConns: 20
  maxOpenConns: 800

# Logging
log:
  level: "DEBUG"

# WorkerPool
workerpool:
  maxPoolSize: 20
  maxQueueSize: 40
