apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  username: 
  password: 
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret-webscraping
type: Opaque
data:
  token: 
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret-proxycrawl
type: Opaque
data:
  token: 
---
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn
type: Opaque
data:
  dsn: 
