// Copyright 2021 Wei (Sam) Wang <sam.wang.0723@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by "stringer -type=source"; DO NOT EDIT.

package handlers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TwseDailyClose-0]
	_ = x[TwseThreePrimary-1]
	_ = x[TpexDailyClose-2]
}

const _source_name = "TwseDailyCloseTwseThreePrimaryTpexDailyClose"

var _source_index = [...]uint8{0, 14, 30, 44}

func (i source) String() string {
	if i < 0 || i >= source(len(_source_index)-1) {
		return "source(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _source_name[_source_index[i]:_source_index[i+1]]
}
