apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    - name: jarvis-service
      port: 8080
      targetPort: 8080
    - name: grafana
      port: 3005
      targetPort: 3005
    - name: prometheus
      port: 3006
      targetPort: 3006
