apiVersion: v1
kind: Secret
metadata:
  namespace: development
  name: database-secret
type: Opaque
data:
  username: YWRtaW4=
  password: aW9yaTIwMDg=
---
apiVersion: v1
kind: Secret
metadata:
  namespace: development
  name: proxy-secret-dailyclose
type: Opaque
data:
  token: OHBfbkRrNy16bzA5SS1QNF9NamtLdw==
---
apiVersion: v1
kind: Secret
metadata:
  namespace: development
  name: proxy-secret-concentration
type: Opaque
data:
  token: THE5THNieEppYmNlMXMyQTlzSUNuQQ==
