// Code generated by "stringer -type=Source"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TwseDailyClose-0]
	_ = x[TwseThreePrimary-1]
	_ = x[TpexDailyClose-2]
	_ = x[TwseStockList-3]
	_ = x[TpexStockList-4]
	_ = x[StakeConcentration-5]
}

const _Source_name = "TwseDailyCloseTwseThreePrimaryTpexDailyCloseTwseStockListTpexStockListStakeConcentration"

var _Source_index = [...]uint8{0, 14, 30, 44, 57, 70, 88}

func (i Source) String() string {
	if i < 0 || i >= Source(len(_Source_index)-1) {
		return "Source(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Source_name[_Source_index[i]:_Source_index[i+1]]
}
