// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcdb

import (
	"github.com/ericlagergren/decimal"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type BalanceView struct {
	ID        uuid.UUID
	Balance   pgtype.Numeric
	Available pgtype.Numeric
	Pending   pgtype.Numeric
	Version   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type DailyClose struct {
	ID           uuid.UUID
	StockID      string
	ExchangeDate string
	TradeShares  *int64
	Transactions *int64
	Turnover     *int64
	Open         decimal.Big
	Close        decimal.Big
	High         decimal.Big
	Low          decimal.Big
	PriceDiff    decimal.Big
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type Order struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	StockID          string
	BuyPrice         decimal.Big
	BuyQuantity      int64
	BuyExchangeDate  string
	SellPrice        decimal.Big
	SellQuantity     int64
	SellExchangeDate string
	ProfitablePrice  decimal.Big
	Status           string
	Version          int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type OrderEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type PickedStock struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	StockID   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type StakeConcentration struct {
	ID              uuid.UUID
	StockID         string
	ExchangeDate    string
	SumBuyShares    *int64
	SumSellShares   *int64
	AvgBuyPrice     decimal.Big
	AvgSellPrice    decimal.Big
	Concentration1  pgtype.Numeric
	Concentration5  pgtype.Numeric
	Concentration10 pgtype.Numeric
	Concentration20 pgtype.Numeric
	Concentration60 pgtype.Numeric
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
}

type Stock struct {
	ID        string
	Name      string
	Country   string
	Site      *string
	Category  *string
	Market    *string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type ThreePrimary struct {
	ID                 uuid.UUID
	StockID            string
	ExchangeDate       string
	ForeignTradeShares *int64
	TrustTradeShares   *int64
	DealerTradeShares  *int64
	HedgingTradeShares *int64
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DeletedAt          pgtype.Timestamp
}

type Transaction struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	OrderID      uuid.UUID
	OrderType    string
	CreditAmount pgtype.Numeric
	DebitAmount  pgtype.Numeric
	Status       string
	Version      int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type TransactionEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID               uuid.UUID
	FirstName        string
	LastName         string
	Email            string
	Phone            string
	Password         string
	SessionID        *string
	EmailConfirmedAt pgtype.Timestamp
	PhoneConfirmedAt pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	SessionExpiredAt pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}
