// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcdb

import (
	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type BalanceView struct {
	ID        uuid.UUID
	Balance   float64
	Available float64
	Pending   float64
	Version   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type DailyClose struct {
	ID           uuid.UUID
	StockID      string
	ExchangeDate string
	TradeShares  *int64
	Transactions *int64
	Turnover     *int64
	Open         float64
	Close        float64
	High         float64
	Low          float64
	PriceDiff    float64
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type Order struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	StockID          string
	BuyPrice         float64
	BuyQuantity      int64
	BuyExchangeDate  string
	SellPrice        float64
	SellQuantity     int64
	SellExchangeDate string
	ProfitablePrice  float64
	Status           string
	Version          int32
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type OrderEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type PickedStock struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	StockID   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type StakeConcentration struct {
	ID              uuid.UUID
	StockID         string
	ExchangeDate    string
	SumBuyShares    *int64
	SumSellShares   *int64
	AvgBuyPrice     float64
	AvgSellPrice    float64
	Concentration1  float64
	Concentration5  float64
	Concentration10 float64
	Concentration20 float64
	Concentration60 float64
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
}

type Stock struct {
	ID        string
	Name      string
	Country   string
	Site      *string
	Category  *string
	Market    *string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type ThreePrimary struct {
	ID                 uuid.UUID
	StockID            string
	ExchangeDate       string
	ForeignTradeShares *int64
	TrustTradeShares   *int64
	DealerTradeShares  *int64
	HedgingTradeShares *int64
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	DeletedAt          pgtype.Timestamp
}

type Transaction struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	OrderID      uuid.UUID
	OrderType    string
	CreditAmount float64
	DebitAmount  float64
	Status       string
	Version      int32
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type TransactionEvent struct {
	AggregateID uuid.UUID
	ParentID    uuid.UUID
	EventType   string
	Payload     []byte
	Version     int32
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID               uuid.UUID
	FirstName        string
	LastName         string
	Email            string
	Phone            string
	Password         string
	SessionID        *string
	EmailConfirmedAt pgtype.Timestamp
	PhoneConfirmedAt pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	SessionExpiredAt pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}
