# Server configurations
server:
  name: "jarvis-api"
  version: "v2.0.1"
  host: "0.0.0.0"
  port: 8080
  grpcPort: 8081

# Database credentials
database:
  host: "mysql-primary-headless.default.svc.cluster.local"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  minIdleConns: 20
  maxOpenConns: 200

replica:
  host: "mysql-secondary-headless.default.svc.cluster.local"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  minIdleConns: 40
  maxOpenConns: 800

kafka:
  brokers: ["kafka-headless.default.svc.cluster.local:9092"]
  topics: ["dailycloses-v1", "stocks-v1", "threeprimary-v1", "stakeconcentration-v1"]
  groupId: "jarvis"

redis:
  sentinelAddrs: ["redis-sentinel-headless.default.svc.cluster.local:26379"]
  master: "mymaster"

# Logging
log:
  level: "debug"
