# Server configurations
server:
  name: "jarvis-api"
  version: "v2.0.1"
  host: "0.0.0.0"
  port: 8080
  grpcPort: 8081

# Database credentials
database:
  host: "localhost"
  port: 5432
  database: "jarvis_main"
  maxLifetime:  10
  minIdleConns: 10
  maxOpenConns: 30

# Logging
log:
  level: "info"
