# Server configurations
server:
  name: "jarvis-api"
  version: "v3.0.0"
  host: "0.0.0.0"
  port: 8080
  grpcPort: 8081

# Database credentials
database:
  host: "localhost" # "host.docker.internal"
  port: "5432"
  database: "jarvis_main"
  maxLifetime:  10
  maxIdleConns: 10
  maxOpenConns: 30

kafka:
  brokers: ["localhost:9092"] # ["host.docker.internal:9092"]
  topics: ["dailycloses-v1", "stocks-v1", "threeprimary-v1", "stakeconcentration-v1"]
  groupId: "jarvis"

redis:
  sentinelAddrs: ["localhost:26379"] # ["host.docker.internal:26379"]
  master: "mymaster"

# Logging
log:
  level: "info"
