# Server configurations
server:
  name: "jarvis"
  host: "0.0.0.0"
  port: 8080
  grpcPort: 8081

# Database credentials
database:
  host: "host.docker.internal"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  maxIdleConns: 20
  maxOpenConns: 200

replica:
  host: "host.docker.internal"
  port: 3306
  database: "jarvis"
  maxLifetime:  10
  maxIdleConns: 20
  maxOpenConns: 800

kafka:
  brokers: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]

# Logging
log:
  level: "ERROR"
