name: "sqlc"

on:
  pull_request:
    paths:
      - 'database/**/*.sql'
      - 'internal/db/main/sqlc/*.sql.go'

jobs:
  sqlc-diff-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Check sqlc diff
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.26.0 && $(go env GOPATH)/bin/sqlc -f ./database/sqlc.yaml diff && echo pass

